### PR TITLE
Adds the Unitree G1 locomotion environment

### PR DESCRIPTION
**Pull request by abizovnuralem**
# Description

Added Unitree G1 example with USD file and policy settings. The USD model was optimized (removed unnecessary collider meshes to boost the training process). The assets https://github.com/abizovnuralem/g1_assets
The tests failed because I needed to upload USD to the nucleus server, I read that I need your help to do that

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Screenshots
2024-06-0322-00-58-ezgif com-video-to-gif-converter (3)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./isaaclab.sh --format`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run all the tests with `./isaaclab.sh --test` and they pass
- [ ] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by abizovnuralem** [comment]
the G1 assets https://github.com/abizovnuralem/g1_assets

**Comment by abizovnuralem** [comment]
tests are failed because I need to upload USD to the nucleus server, I read that I need your help to do that

**Comment by Dhoeller19** [comment]
Hi @abizovnuralem, 
This is really cool, thanks! It seems like the flat terrain locomotion doesn't work so well. I am tuning on my side a bit and will update the MR.

**Comment by abizovnuralem** [comment]
@Dhoeller19 Thank you! FYI the doc image screenshot on the flat terrain is another my experiment, just thought it was funny to put it there, but on the flat terrain the robot walks the same as on rough terrain , if you want I can put original screenshot there to make it more clear

**Comment by abizovnuralem** [comment]
This is an example of flat terrain 
Screencastfrom06-05-2024121510PM-ezgif com-crop

**Comment by Dhoeller19** [comment]
Okay, I am making sure the assets get uploaded to the Nucleus server. 

Quick question, you put armature values of 0.1 to all the joints, which seems a bit high to me.
Where did you take these values from? In the mujoco file [here](https://github.com/unitreerobotics/unitree_ros/blob/master/robots/g1_description/g1.xml#L5)., it seems to indicate that they use 0.01. 
But in general, I don't think it should be necessary.

**Comment by abizovnuralem** [comment]
I took 0.1 armature values from the H1 urdf example, that was provided here
image

**Comment by Dhoeller19** [comment]
Okay I see, the 0.1 for H1 comes from [here](https://github.com/unitreerobotics/unitree_ros/blob/master/robots/h1_description/mjcf/h1.xml#L7).
I will quickly play around with 0.01

**Comment by abizovnuralem** [comment]
Interesting point, David! I have tried now both 0.1 (pink) and 0.01 (blue) on flat terrain and got this:

image

I hope this info will be helpful

**Comment by abizovnuralem** [comment]
Good point, David! I have trained now both 0.1 (red) and 0.01 (blue) to compare them and here are some interesting results:

image

The only big difference is joint_deviation_torso. I hope it will be helpful.

**Comment by abizovnuralem** [comment]
You did a huge work with this PR, @Dhoeller19 , thank you so much!  Small updates are not so "small", haha))

**Review by Dhoeller19 — APPROVED** [review]

**Pull request merged**
