### PR TITLE
Reorganizes the structure to drop `omni.isaac` and directly use `isaaclab` as extension name

### PR DESCRIPTION
**Pull request by pascal-roth**
# Description

Reorganize the extensions to achieve a simpler and easier-to-understand structure. We make use of Kit 106, which drops the requirement to have the extension name as a composition of at least two elements separated by a dot and instead allows for a single word as name. Consequently, the extensions are renamed as follows:

- `omni.isaac.lab` --> `isaaclab`
- `omni.isaac.lab_tasks` --> `isaaclab_tasks`
- `omni.isaac.lab_assets` --> `isaaclab_assets`

This reduces the structure from `omni.isaac.lab/omni/isaac/lab` to `isaaclab/isaaclab`. 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshots

While extensions can still be found as expected

Screenshot from 2024-06-24 18-15-43

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run all the tests with `./isaaclab.sh --test` and they pass
- [ ] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by Mayankm96** [comment]
Does this also work with Isaac Sim 2023.1.1? Just wondering if Kit 105.1 already supported a single extension name. Otherwise, this change also means a drop in support for 2023.1.1.

**Comment by pascal-roth** [comment]
@Mayankm96 I can test it but are we backward compatible in general so far with the code changes?

**Comment by pascal-roth** [comment]
also after merging #617  and #616 (introducing a Velodyne lidar and zed depth cameras), a further split of the assets into robots and sensors necessary

**Comment by Mayankm96** [comment]
@pascal-roth We discussed this internally, and Isaac Sim will change its extension naming following a style similar to the above in November. We have received push-back to do this change as it will break the user's experience twice (once now and again in November when Isaac Sim breaks the APIs). Hence, we have also decided to do this in November with Isaac Sim.

**Comment by pascal-roth** [comment]
There is no need for a review now; will be addressed in November when IsaacSim will also be renamed. Keep the PR open as information.

**Comment by pascal-roth** [comment]
closed for now, will be picked up in the new release

**Pull request closed without merging**
