### PR TITLE
Fixes actuator velocity limits propagation down the articulation root_physx_view

### LINKED ISSUE #1384: [Bug Report] Incorrect dof max velocities for explicit actuators
### Describe the bug

When using explicit actuators in an articulation, the max dof velocity is not set properly. For explicit actuators, the articulation root_physx_view seemingly should set the max_dof_velocity of the implicit actuator to a large number, similar to how effort limits are handled. This is particularly true for explicit actuators that implement a velocity limit, but exactly how it should be handled in general is unclear. 

### Steps to reproduce

Instantiate any model using explicit actuators and velocity limits greater than the default physx max dof velocity limits. 

### System Info

Describe the characteristic of your environment:

- Commit: b9a49ca
- Isaac Sim Versions: 4.0.0-4.2.0
- OS: [e.g. Ubuntu 22.04]
- GPU: [e.g. NVIDIA RTX 4090]
- CUDA: [e.g. 12.1]
- GPU Driver: [e.g. 535.183.01 and 550.120]

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

- [ ] The velocity limits should be lifted for explicit actuators.

### PR DESCRIPTION
**Pull request by jtigue-bdai**
# Description

Previously the velocity limits of the the ActuatorBaseCfg do not get used in most actuators. Only the DCMotor actuator uses it but it only uses it for torque-speed limitations. 

This PR propagates the velocity_limits of the ActuatorBaseCfg to the articulation root_physx_view. 

Fixes #1384 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

Please attach before and after screenshots of the change if applicable.

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./isaaclab.sh --format`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Review by kellyguo11 — APPROVED** [review]

**Comment by larsrpe** [comment]
This seems like a nice feature for consistency through the different layers. However, I wonder if this can have implications for the simulator performance, depending on how this constraint is implemented in the backend. 

I think one potential issue is when using the DCMotor model we want to define a torque cutoff speed to obtain more realistic speed torque relationship, however this does not  necessarily mean that we want to have a hard limit on the joint velocities, which might give simulation artefacts.  

I think follow up work should be to separate the velocity limit used in the DC motor model and the one used for the hard physics limit. What do you think?

**Comment by jtigue-bdai** [comment]
That’s a good point. The velocity_limit is being used as the “no load
speed” which works for active motor torques. But with external loading,
motors can operate in another quadrant of the torque-speed curve producing
more speed.

It should be straightforward to not physically cap the velocity for the
DCMotor.

<https://theaiinstitute.com/>

*James Tigue, PhD*

*Simulation Software Engineer*

The AI Institute

theaiinstitute.com

**Comment by larsrpe** [comment]
Should we instead use` self._no_load_speed` here:

https://github.com/isaac-sim/IsaacLab/blob/4ee4957e0880240169d2cd6a68b6f4b3d32bcdc7/source/extensions/omni.isaac.lab/omni/isaac/lab/actuators/actuator_pd.py#L226

This would only require adding one field to the `DCMotorCfg`.

**Comment by Mayankm96** [comment]
I agree with @larsrpe. Solver-level limits are different from the explicit model considerations. For explicit models, we may want to do the clipping inside the model but not have PhysX apply any of that within it (as tight constraints may lead to undefined behaviors).

For most of the shared quantities, we should maybe have their counterpart quantities as "torque_limit_sim" and "velocity_limit_sim". This makes it clear that these are being set at the solver level always. Their default values can be high (as right now).

**Pull request merged**
