### PR TITLE
Add `OperationSpaceController` to docs and tests

### LINKED ISSUE #873: [Question] Implementation status of the operational space and joint impedance controllers
Hello everyone, 

I need to use an operational space controller for some manipulation tasks in the context of RL/sim2real. I have noticed that an implementation of such a controller already exists in the [controllers folder](https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/omni/isaac/lab/controllers/operational_space.py), along with some other task-space controllers. However, I do not see these in the API documentation, and the last changes on these files were quite some time ago. 

Are these controllers (e.g., operational space and joint impedance controllers) fully functional for RL at the moment, or do they have any limitations that need to be solved?

### PR DESCRIPTION
**Pull request by jtigue-bdai**
# Description

This PR add the `OperationSpaceController` to the docs and provides some test for its parameteric features. 

Fixes #873  

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Screenshots

Please attach before and after screenshots of the change if applicable.

## Checklist

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [ ] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by ozhanozen** [comment]
@jtigue-bdai, shall we also include in this PR, adding a corresponding action class, i.e., OperationSpaceControllerAction/Cfg, [here](https://github.com/isaac-sim/IsaacLab/blob/docs/operation_space_controller/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/actions/task_space_actions.py)? This would be nice for being able to interface it with the action manager, and such exist for other controllers.

**Comment by jtigue-bdai** [comment]
Yeah I think that would be a good addition with this effort.

**Comment by ozhanozen** [comment]
@jtigue-bdai At the moment I do not have push access to this PR branch. 

Would you prefer I create a new PR from my own fork to integrate into this PR (so there would be two different PRs for the same topic), or would you like to give me push access to this branch? If you will give access, could you do it for both @ozhanozen and @sbtc-sipbb?

**Comment by jtigue-bdai** [comment]
Sorry @ozhanozen my intention was for you to push to this branch, but let me check with the dev team this morning and I will get back to you.

**Comment by jtigue-bdai** [comment]
@ozhanozen I talked with the team. Because this repo is setup within the isaac-sim org, the best way moving forward will be to have you create the PR from your fork and to the isaac-sim/isaac-lab. We can then just close this one and I can give you reviews you your branch.

Sorry for the confusion, I didn't realize some of the restrictions we had setup.

**Comment by ozhanozen** [comment]
@jtigue-bdai no problem. I have created a new PR from my fork, #913, as you suggested, and we can work on it.

You can close this PR.

**Comment by jtigue-bdai** [comment]
Closing in favor of #913 for OS user contributions

**Pull request closed without merging**
