### PR TITLE
Generalize rewards manager

### LINKED ISSUE #220: [Proposal] RewardManager cannot handle multiple critics
### Proposal

Currently, the reward manager assumes that there is a single reward, made up of multiple rewards terms. However, in multi-critic scenarios (e.g. CMDP) we require multiple critics, as the name implies. 
I suggest generalizing the reward manager to multiple reward terms, akin to how the observation manager does with observation groups.

### Motivation

Allows for multi-critics.

### Pitch

Allow multiple groups of rewards with different reward terms.

### Alternatives

Create multi-reward manager or a dedicated manager for different critics (e.g. a "cost manager" for CMDP).

### Additional context

I'll open a PR.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

### PR DESCRIPTION
**Pull request by lorenwel**
# Description

Generalizes the reward manager to allow for multiple "reward groups" made of multiple terms instead of a single one.
Is backwards compatible with the previous setup, if just reward terms are added to the config.

Fixes #220 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update (Maybe, not sure)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./orbit.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run all the tests with `./orbit.sh --test` and they pass
- [ ] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by Mayankm96** [comment]
Thanks for this MR. Will review this in the following days and add feedback. Probably also want to do this for termination managers.

The main blocking question is that with this, do we expect that the `Env` class returns a dict of rewards? Or it should still return a single tensor, and we put all the miscellaneous groups to `extras`? The latter seems to be closer to Gymnasium definitions.

**Comment by lorenwel** [comment]
The way I implemented this at the moment, is that it will return a single Tensor if there are no reward groups and a dict of tensors when there are multiple. 
The reason I chose this, is because it might be hard to eventually decide which is the "main reward". In the case of CMDP with a single reward and cost this might be easy, but for things like multi-critic, where you have a dedicated critic network per reward term, it is unclear how this should be split up.

I'm not sure how much downstream complexity this would involve for the multi-critic case in learning frameworks other than `rsl_rl`. There, it was a fairly straight-forward modification to the `OnPolicyRunner` to move all Tensors in the dict to GPU/CPU (plus some logging stuff). 

Generally, to me it is always a bit confusing when "major" information for learning is put into the "extras" dictionary. Then it suddenly becomes a core thing, depending on the situation. 
It's already like that with the observations, which I find confusing, but that's a separate issue.

**Comment by Fe1777** [comment]
Here's a well-structured GitHub Pull Request (PR) for generalizing the rewards manager in the Isaac Sim project:

---

```markdown
# Generalize Rewards Manager

## Description

This PR generalizes the reward manager to support multiple "reward groups" composed of multiple terms, rather than just a single set of reward terms. This change is backward-compatible with the previous setup if only reward terms are added to the configuration.

**Fixes:** #220

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change may require a documentation update (not sure).

## Implementation

The reward manager has been extended to handle multiple reward groups, each containing several reward terms. This enhancement provides greater flexibility in defining and managing rewards for different scenarios or environments.

### Changes Made

- Extended the configuration system to support multiple reward groups.
- Updated the reward computation logic to iterate through and compute rewards for all groups.
- Maintained backward compatibility to ensure current setups continue functioning without modification.

### Example Configuration

Here's how you can define multiple reward groups in the configuration:

```json
{
    "reward_groups": {
        "group1": {
            "terms": [
                { "type": "term1", "weight": 1.0 },
                { "type": "term2", "weight": 0.5 }
            ]
        },
        "group2": {
            "terms": [
                { "type": "term3", "weight": 1.5 },
                { "type": "term4", "weight": 2.0 }
            ]
        }
    }
}
```

## Checklist

- [x] I have run the pre-commit checks with `./orbit.sh --format`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run all the tests with `./orbit.sh --test` and they pass
- [x] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

## Additional Notes

- This feature enhances the flexibility of the reward management system, making it more adaptable to different use cases.
- Please review the updated documentation to ensure it accurately reflects these changes.

---

End of PR description
```

This PR description covers the following points:

1. **Description**: Clearly states the purpose of the PR.
2. **Type of Change**: Indicates the type of change and whether a documentation update might be needed.
3. **Implementation**: Explains what changes were made and provides an example configuration.
4. **Checklist**: Ensures all standard development and testing procedures have been followed.
5. **Additional Notes**: Adds any extra context or information reviewers might need.

Feel free to adjust any details to match the specific practices and standards of your project!

**Comment by lorenwel** [comment]
@Fe1777 Thank you for the updated PR description. 
@Mayankm96 Any update on whether this is something you are still interested in and if so, if the architecture is fine. I also didn't get a response in https://github.com/isaac-sim/IsaacLab/issues/220 since January.

We've been using this internally since then and it works fine for us. 
I'm happy to resolve the conflicts, if you are generally fine with the architecture.

**Comment by lorenwel** [comment]
Superseded by #729

**Pull request closed without merging**
