### PR TITLE
Feature/lidar sensor

### PR DESCRIPTION
**Pull request by LukasVindbjerg**
# Description

Dear Isaac Lab maintainers, 

We have been working with some code for wrapping the Isaac sim lidar prim described in the documentation here:
https://docs.omniverse.nvidia.com/isaacsim/latest/advanced_tutorials/tutorial_advanced_range_sensor_lidar.html

The code is heavily inspired by the camera sensor class. 

We know that the code in its current state does not integrate well with your new release of Isaac Lab. Before we go ahead and put more time into fixing the code and completing the checklist, we would like to ask you if this code is of interest to you. The code is a product of this discussion: https://github.com/isaac-sim/IsaacLab/discussions/291

Note: This code does not work in headless mode unless the `range_sensor` dependency is added in Isaac sim headless. 

## Type of change

- New feature (non-breaking change which adds functionality)

## Screenshots
LiDAR_beams

## Checklist

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run all the tests with `./isaaclab.sh --test` and they pass
- [ ] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [ ] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by jtigue-bdai** [comment]
Hi @LukasVindbjerg, yes I think this kind of sensor would be a good addition to IsaacLab. I can work with you to get this integrated.

**Comment by LukasVindbjerg** [comment]
Hi @jtigue-bdai, that sounds great.
We will start working on it from next week.

**Comment by Mayankm96** [comment]
Hi @LukasVindbjerg and @jtigue-bdai 

Thank you for bringing this up. From what I see, the MR currently uses the PhysX based implementation of the LiDAR sensor. I think this is pretty limiting as it only checks against geometric colliders.

I think it is better to move the implementation to use RTX-based sensor since that will capture the LiDAR noise better. More information here: https://docs.omniverse.nvidia.com/isaacsim/latest/features/sensors_simulation/isaac_sim_sensors_rtx_based_lidar.html

**Comment by MaltheT** [comment]
> Hi @LukasVindbjerg and @jtigue-bdai
> 
> Thank you for bringing this up. From what I see, the MR currently uses the PhysX based implementation of the LiDAR sensor. I think this is pretty limiting as it only checks against geometric colliders.
> 
> I think it is better to move the implementation to use RTX-based sensor since that will capture the LiDAR noise better. More information here: https://docs.omniverse.nvidia.com/isaacsim/latest/features/sensors_simulation/isaac_sim_sensors_rtx_based_lidar.html

Thanks for pointing this out, we weren't aware of this advantage of using the RTX-based version. However, a complete code rework would be needed to use the RTX version instead of the PhysX. 

Would you prefer us to start working on this transition to the RTX-based sensor, or should we proceed with completing the existing checklist and making the necessary adjustments to integrate the current PhysX-based implementation?

**Comment by Mayankm96** [comment]
I tis unclear what benefits the PhysX LiDAR implementation will bring since it uses CPU ray-cast operations that will be very slow for batched training. I propose to go for RTX directly since it will be more realistic and long-term supported from Isaac Sim side as well.

**Comment by jtigue-bdai** [comment]
@LukasVindbjerg, are you planning on implementing an RTX LiDAR, if not we can close this PR and look at that implementation withing the dev team.

**Comment by jtigue-bdai** [comment]
Thanks @LukasVindbjerg, best of luck.

**Comment by jakethesnake420** [comment]
I'm working on RTX Lidar Ray Caster. This is my first time using isaac so my pr will need work to get merged. Also not focusing on performance at first, just working on the interface.

**Comment by jtigue-bdai** [comment]
> I'm working on RTX Lidar Ray Caster. This is my first time using isaac so my pr will need work to get merged. Also not focusing on performance at first, just working on the interface.

Ok add me as a reviewer when you are ready. I can help work it into the codebase.

**Comment by shaoxiang** [comment]
**Note: This code does not work in headless mode unless the range_sensor dependency is added in Isaac sim headless.**
Thank you very much for your contribution. I would like to ask for your advice **how to added the range_densor dependency in headless.** Because I want to train in headless mode. Thanks.  @LukasVindbjerg

**Comment by shaoxiang** [comment]
Unfortunately, in headless mode, range_sensor data is not updated. Does anyone know how to solve it? Thank you.

**Pull request closed without merging**
