### PR TITLE
Fixes configclass dict conversion for torch tensors

### PR DESCRIPTION
**Pull request by lgulich**
# Description

Fix configclass dict conversion for torch tensors

Up to v1.2.0 if a configclass would contain a list/tuple of torch
tensors it would be left as is.

\#1227 changed the behavior of converting lists/tuples in a dict, which
means that currently torch tensors are converted to an empty dict,
effectively losing all contained data.

The underlying issue is that `torch.tensor.__dict__` returns an empty
dict, which was (luckily) ignored previously because we did not convert
the contents of lists.

This MR fixes this by treating torch tensors specially. I don't like
having a special case for a non-builtin class but given that
IsaacLab is heavily married with torch tensors I think it's ok in this
case.

Since currently the behavior is different between 1.2 and 1.3: can we cherry pick this change to the 1.3 branch?

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by mschweig** [comment]
Hi @lgulich, @kellyguo11 

this PR causes issues with `rsl_rl/train.py `and Boston Dynamics Spot `joint_parameter_lookup`which is `torch.tensor`

https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab_assets/omni/isaac/lab_assets/spot.py

In this case `torch.tensor.__dict__` does not return an empty dict and this works in 1.3.0. 

This PR changes the behavior and returns the tensor object instead of converting `obj.__dict__`  to a dict.
But this implementation raises a omegaconf exception with rsl_rl train: 

`omegaconf.errors.UnsupportedValueType: Value 'Tensor' is not a supported primitive type`

I am quite new to Isaac Lab, however would be happy to help and fix this one.

**Comment by lgulich** [comment]
Hi @mschweig 

I'm happy to help. Any chance you could add a unit test in this [file](https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/test/utils/test_configclass.py)?

Then I can take a look to make sure that it's fixed.

**Comment by mschweig** [comment]
Hi @lgulich

sure, gonna add a dummy `ActuatorCfg` and a unittest that checks if the `__dict__` conversion does not return an empty dict.

**Comment by mschweig** [comment]
Hi @lgulich 

added a unittest and created a PR:

https://github.com/isaac-sim/IsaacLab/pull/1608

The test fails as I expect according to my understanding. Should I open a issue to track it?

**Pull request merged**
